
# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/neutronics-workflow:dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run example_01_single_volume_cell_tally
        run: |
          cd example_01_single_volume_cell_tally/
          python stage_1_create_cad.py
          python stage_2_convert_cad_to_neutronics.py
          python stage_3_run_neutronics_simulation.py  
        
      - name: run example_02_multi_volume_cell_tally
        run: |
          cd example_02_multi_volume_cell_tally/
          python stage_1_create_cad.py
          python stage_2_convert_cad_to_neutronics.py
          python stage_3_run_neutronics_simulation.py          

      - name: run example_05_3D_unstructured_mesh_tally
        run: |
          cd example_05_3D_unstructured_mesh_tally/
          python stage_1_create_cad.py
          python stage_2_convert_cad_to_neutronics.py
          mbconvert stage_2_output/unstructured_mesh.cub stage_2_output/unstructured_mesh.h5m
          python stage_3_run_neutronics_simulation.py          
